version: '3.2'
services:
    # nginx
    web:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini:ro
            - ./app:/var/www/html

    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            target: '${BUILD_TARGET:-app}'
        volumes:
            - ./app:/var/www/html
        environment:
            MYSQL_HOST: db
            MYSQL_PORT: ${MYSQL_PORT}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            REDIS_HOST: cache
            REDIS_PORT: ${REDIS_PORT}
            XDEBUG_MODE: '${XDEBUG_MODE:-off}' # See https://xdebug.org/docs/all_settings#mode
        extra_hosts:
            # Ensure that host.docker.internal is correctly defined on Linux
            - host.docker.internal:host-gateway

    # mysql
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD} # Default root user password.
            MYSQL_USER: ${MYSQL_USER} # User with limited permissions.
            MYSQL_PASSWORD: ${MYSQL_PASSWORD} # User with limited permissions.
            MYSQL_DATABASE: ${MYSQL_DATABASE} # Default schema, the above user will have access.
        ports:
            - 3306:3306
        volumes:
            - mysqldata:/var/lib/mysql

    # redis
    cache:
        image: redis:latest

volumes:
    mysqldata: {}
