version: '3.2'
services:
    # nginx
    web:
        image: nginx:latest
        ports:
            - 80:80
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
            - ./app:/var/www/html

    # php
    app:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        volumes:
            - ./app:/var/www/html

    # mysql
    db:
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: 'dev' # Default root user password.
            MYSQL_USER: 'demo' # User with limited permissions.
            MYSQL_PASSWORD: 'demo' # User with limited permissions.
            MYSQL_DATABASE: 'app' # Default schema, the above user will have access.
        ports:
            - 3306:3306
        volumes:
            - mysqldata:/var/lib/mysql

    # redis

volumes:
    mysqldata: {}
